import type { CommunityMarketTier } from "@/lib/community/markets";

export type CommunityMarketSeed = {
  slug: string;
  name: string;
  county_name: string;
  city: string;
  state: "PA" | "NJ";
  region: string;
  location_query: string;
  latitude: number;
  longitude: number;
  radius_miles: number;
  market_tier: CommunityMarketTier;
  sync_frequency_hours: number;
  sort_order: number;
  city_anchors: string[];
  max_queries_per_sync: number;
  search_terms: string[];
};

const PET_TERMS = [
  "pet events",
  "dog adoption events",
  "pet adoption events",
  "animal rescue events",
  "pet expo",
  "dog festival",
  "pet friendly events",
  "dog walk fundraiser",
];

/** Canonical PA/NJ discovery markets — SerpApi syncs events inside these. */
export const COMMUNITY_MARKET_SEEDS: CommunityMarketSeed[] = [
  {
    slug: "philadelphia-pa",
    name: "Philadelphia, PA",
    county_name: "Philadelphia County",
    city: "Philadelphia",
    state: "PA",
    region: "Greater Philadelphia",
    location_query: "Philadelphia, Pennsylvania",
    latitude: 39.9526,
    longitude: -75.1652,
    radius_miles: 25,
    market_tier: "core",
    sync_frequency_hours: 24,
    sort_order: 5,
    city_anchors: ["Philadelphia"],
    max_queries_per_sync: 1,
    search_terms: PET_TERMS,
  },
  {
    slug: "bucks-county-pa",
    name: "Bucks County, PA",
    county_name: "Bucks County",
    city: "Doylestown",
    state: "PA",
    region: "Greater Philadelphia",
    location_query: "Bucks County, Pennsylvania",
    latitude: 40.3101,
    longitude: -75.131,
    radius_miles: 35,
    market_tier: "core",
    sync_frequency_hours: 24,
    sort_order: 10,
    city_anchors: ["Doylestown", "Newtown", "Quakertown", "Yardley"],
    max_queries_per_sync: 1,
    search_terms: PET_TERMS,
  },
  {
    slug: "montgomery-county-pa",
    name: "Montgomery County, PA",
    county_name: "Montgomery County",
    city: "King of Prussia",
    state: "PA",
    region: "Greater Philadelphia",
    location_query: "Montgomery County, Pennsylvania",
    latitude: 40.0892,
    longitude: -75.3397,
    radius_miles: 35,
    market_tier: "core",
    sync_frequency_hours: 24,
    sort_order: 20,
    city_anchors: ["King of Prussia", "Lansdale", "Pottstown", "Ambler"],
    max_queries_per_sync: 1,
    search_terms: PET_TERMS,
  },
  {
    slug: "chester-county-pa",
    name: "Chester County, PA",
    county_name: "Chester County",
    city: "West Chester",
    state: "PA",
    region: "Greater Philadelphia",
    location_query: "Chester County, Pennsylvania",
    latitude: 39.9601,
    longitude: -75.606,
    radius_miles: 35,
    market_tier: "core",
    sync_frequency_hours: 24,
    sort_order: 25,
    city_anchors: ["West Chester", "Exton", "Downingtown", "Phoenixville"],
    max_queries_per_sync: 1,
    search_terms: PET_TERMS,
  },
  {
    slug: "delaware-county-pa",
    name: "Delaware County, PA",
    county_name: "Delaware County",
    city: "Media",
    state: "PA",
    region: "Greater Philadelphia",
    location_query: "Delaware County, Pennsylvania",
    latitude: 39.9187,
    longitude: -75.3877,
    radius_miles: 30,
    market_tier: "growth",
    sync_frequency_hours: 24,
    sort_order: 28,
    city_anchors: ["Media", "Springfield"],
    max_queries_per_sync: 1,
    search_terms: PET_TERMS,
  },
  {
    slug: "lehigh-county-pa",
    name: "Lehigh County, PA",
    county_name: "Lehigh County",
    city: "Allentown",
    state: "PA",
    region: "Lehigh Valley",
    location_query: "Lehigh County, Pennsylvania",
    latitude: 40.6084,
    longitude: -75.4902,
    radius_miles: 35,
    market_tier: "core",
    sync_frequency_hours: 24,
    sort_order: 30,
    city_anchors: ["Allentown", "Bethlehem"],
    max_queries_per_sync: 1,
    search_terms: PET_TERMS,
  },
  {
    slug: "berks-county-pa",
    name: "Berks County, PA",
    county_name: "Berks County",
    city: "Reading",
    state: "PA",
    region: "Reading / Lehigh Valley",
    location_query: "Berks County, Pennsylvania",
    latitude: 40.3356,
    longitude: -75.9269,
    radius_miles: 35,
    market_tier: "growth",
    sync_frequency_hours: 24,
    sort_order: 35,
    city_anchors: ["Reading", "Wyomissing"],
    max_queries_per_sync: 1,
    search_terms: PET_TERMS,
  },
  {
    slug: "northampton-county-pa",
    name: "Northampton County, PA",
    county_name: "Northampton County",
    city: "Bethlehem",
    state: "PA",
    region: "Lehigh Valley",
    location_query: "Northampton County, Pennsylvania",
    latitude: 40.6259,
    longitude: -75.3705,
    radius_miles: 35,
    market_tier: "core",
    sync_frequency_hours: 24,
    sort_order: 40,
    city_anchors: ["Bethlehem", "Easton", "Nazareth"],
    max_queries_per_sync: 1,
    search_terms: PET_TERMS,
  },
  {
    slug: "warren-county-nj",
    name: "Warren County, NJ",
    county_name: "Warren County",
    city: "Phillipsburg",
    state: "NJ",
    region: "Lehigh Valley",
    location_query: "Warren County, New Jersey",
    latitude: 40.6937,
    longitude: -75.1902,
    radius_miles: 30,
    market_tier: "seasonal",
    sync_frequency_hours: 168,
    sort_order: 42,
    city_anchors: ["Phillipsburg", "Washington"],
    max_queries_per_sync: 1,
    search_terms: PET_TERMS,
  },
  {
    slug: "burlington-county-nj",
    name: "Burlington County, NJ",
    county_name: "Burlington County",
    city: "Mount Laurel",
    state: "NJ",
    region: "Greater Philadelphia",
    location_query: "Burlington County, New Jersey",
    latitude: 39.952,
    longitude: -74.903,
    radius_miles: 30,
    market_tier: "growth",
    sync_frequency_hours: 24,
    sort_order: 45,
    city_anchors: ["Mount Holly", "Mount Laurel", "Burlington"],
    max_queries_per_sync: 1,
    search_terms: PET_TERMS,
  },
  {
    slug: "camden-county-nj",
    name: "Camden County, NJ",
    county_name: "Camden County",
    city: "Cherry Hill",
    state: "NJ",
    region: "Greater Philadelphia",
    location_query: "Camden County, New Jersey",
    latitude: 39.9348,
    longitude: -75.0307,
    radius_miles: 30,
    market_tier: "growth",
    sync_frequency_hours: 24,
    sort_order: 48,
    city_anchors: ["Cherry Hill", "Haddonfield", "Voorhees"],
    max_queries_per_sync: 1,
    search_terms: PET_TERMS,
  },
  {
    slug: "gloucester-county-nj",
    name: "Gloucester County, NJ",
    county_name: "Gloucester County",
    city: "Sewell",
    state: "NJ",
    region: "Greater Philadelphia",
    location_query: "Gloucester County, New Jersey",
    latitude: 39.7465,
    longitude: -75.1113,
    radius_miles: 30,
    market_tier: "growth",
    sync_frequency_hours: 24,
    sort_order: 50,
    city_anchors: ["Deptford", "Washington Township"],
    max_queries_per_sync: 1,
    search_terms: PET_TERMS,
  },
  {
    slug: "monmouth-county-nj",
    name: "Monmouth County, NJ",
    county_name: "Monmouth County",
    city: "Freehold",
    state: "NJ",
    region: "Jersey Shore",
    location_query: "Monmouth County, New Jersey",
    latitude: 40.2601,
    longitude: -74.2735,
    radius_miles: 35,
    market_tier: "growth",
    sync_frequency_hours: 24,
    sort_order: 60,
    city_anchors: ["Freehold", "Red Bank", "Asbury Park"],
    max_queries_per_sync: 1,
    search_terms: PET_TERMS,
  },
  {
    slug: "ocean-county-nj",
    name: "Ocean County, NJ",
    county_name: "Ocean County",
    city: "Toms River",
    state: "NJ",
    region: "Jersey Shore",
    location_query: "Ocean County, New Jersey",
    latitude: 39.9537,
    longitude: -74.1979,
    radius_miles: 35,
    market_tier: "growth",
    sync_frequency_hours: 24,
    sort_order: 62,
    city_anchors: ["Toms River", "Point Pleasant", "Brick"],
    max_queries_per_sync: 1,
    search_terms: PET_TERMS,
  },
  {
    slug: "atlantic-county-nj",
    name: "Atlantic County, NJ",
    county_name: "Atlantic County",
    city: "Egg Harbor Township",
    state: "NJ",
    region: "Jersey Shore",
    location_query: "Atlantic County, New Jersey",
    latitude: 39.4024,
    longitude: -74.5626,
    radius_miles: 35,
    market_tier: "seasonal",
    sync_frequency_hours: 168,
    sort_order: 64,
    city_anchors: ["Egg Harbor Township", "Atlantic City", "Ventnor"],
    max_queries_per_sync: 1,
    search_terms: PET_TERMS,
  },
  {
    slug: "cape-may-county-nj",
    name: "Cape May County, NJ",
    county_name: "Cape May County",
    city: "Cape May",
    state: "NJ",
    region: "Jersey Shore",
    location_query: "Cape May County, New Jersey",
    latitude: 38.9351,
    longitude: -74.906,
    radius_miles: 30,
    market_tier: "seasonal",
    sync_frequency_hours: 168,
    sort_order: 66,
    city_anchors: ["Cape May", "Wildwood", "Ocean City"],
    max_queries_per_sync: 1,
    search_terms: PET_TERMS,
  },
  {
    slug: "mercer-county-nj",
    name: "Mercer County, NJ",
    county_name: "Mercer County",
    city: "Princeton",
    state: "NJ",
    region: "Central Jersey",
    location_query: "Mercer County, New Jersey",
    latitude: 40.3573,
    longitude: -74.6672,
    radius_miles: 30,
    market_tier: "growth",
    sync_frequency_hours: 24,
    sort_order: 70,
    city_anchors: ["Princeton", "Trenton", "Hamilton"],
    max_queries_per_sync: 1,
    search_terms: PET_TERMS,
  },
  {
    slug: "middlesex-county-nj",
    name: "Middlesex County, NJ",
    county_name: "Middlesex County",
    city: "New Brunswick",
    state: "NJ",
    region: "Central Jersey",
    location_query: "Middlesex County, New Jersey",
    latitude: 40.4862,
    longitude: -74.4518,
    radius_miles: 30,
    market_tier: "expansion",
    sync_frequency_hours: 60,
    sort_order: 72,
    city_anchors: ["New Brunswick", "Edison", "Metuchen"],
    max_queries_per_sync: 1,
    search_terms: PET_TERMS,
  },
  {
    slug: "somerset-county-nj",
    name: "Somerset County, NJ",
    county_name: "Somerset County",
    city: "Bridgewater",
    state: "NJ",
    region: "Central Jersey",
    location_query: "Somerset County, New Jersey",
    latitude: 40.5934,
    longitude: -74.6049,
    radius_miles: 30,
    market_tier: "growth",
    sync_frequency_hours: 24,
    sort_order: 74,
    city_anchors: ["Bridgewater", "Somerville"],
    max_queries_per_sync: 1,
    search_terms: PET_TERMS,
  },
  {
    slug: "bergen-county-nj",
    name: "Bergen County, NJ",
    county_name: "Bergen County",
    city: "Paramus",
    state: "NJ",
    region: "North Jersey",
    location_query: "Bergen County, New Jersey",
    latitude: 40.9445,
    longitude: -74.0754,
    radius_miles: 30,
    market_tier: "expansion",
    sync_frequency_hours: 60,
    sort_order: 80,
    city_anchors: ["Paramus", "Hackensack", "Fort Lee"],
    max_queries_per_sync: 1,
    search_terms: PET_TERMS,
  },
  {
    slug: "essex-county-nj",
    name: "Essex County, NJ",
    county_name: "Essex County",
    city: "Montclair",
    state: "NJ",
    region: "North Jersey",
    location_query: "Essex County, New Jersey",
    latitude: 40.8259,
    longitude: -74.209,
    radius_miles: 25,
    market_tier: "expansion",
    sync_frequency_hours: 60,
    sort_order: 82,
    city_anchors: ["Montclair", "West Orange", "Maplewood"],
    max_queries_per_sync: 1,
    search_terms: PET_TERMS,
  },
  {
    slug: "hudson-county-nj",
    name: "Hudson County, NJ",
    county_name: "Hudson County",
    city: "Jersey City",
    state: "NJ",
    region: "North Jersey",
    location_query: "Hudson County, New Jersey",
    latitude: 40.7178,
    longitude: -74.0431,
    radius_miles: 20,
    market_tier: "expansion",
    sync_frequency_hours: 60,
    sort_order: 84,
    city_anchors: ["Jersey City", "Hoboken", "Bayonne"],
    max_queries_per_sync: 1,
    search_terms: PET_TERMS,
  },
  {
    slug: "union-county-nj",
    name: "Union County, NJ",
    county_name: "Union County",
    city: "Westfield",
    state: "NJ",
    region: "North Jersey",
    location_query: "Union County, New Jersey",
    latitude: 40.659,
    longitude: -74.3474,
    radius_miles: 25,
    market_tier: "expansion",
    sync_frequency_hours: 60,
    sort_order: 86,
    city_anchors: ["Westfield", "Summit", "Elizabeth"],
    max_queries_per_sync: 1,
    search_terms: PET_TERMS,
  },
  {
    slug: "morris-county-nj",
    name: "Morris County, NJ",
    county_name: "Morris County",
    city: "Morristown",
    state: "NJ",
    region: "North Jersey",
    location_query: "Morris County, New Jersey",
    latitude: 40.7968,
    longitude: -74.4815,
    radius_miles: 30,
    market_tier: "expansion",
    sync_frequency_hours: 60,
    sort_order: 88,
    city_anchors: ["Morristown", "Madison", "Parsippany"],
    max_queries_per_sync: 1,
    search_terms: PET_TERMS,
  },
  {
    slug: "passaic-county-nj",
    name: "Passaic County, NJ",
    county_name: "Passaic County",
    city: "Wayne",
    state: "NJ",
    region: "North Jersey",
    location_query: "Passaic County, New Jersey",
    latitude: 40.9254,
    longitude: -74.2765,
    radius_miles: 25,
    market_tier: "expansion",
    sync_frequency_hours: 60,
    sort_order: 90,
    city_anchors: ["Wayne", "Clifton", "Passaic"],
    max_queries_per_sync: 1,
    search_terms: PET_TERMS,
  },
];

/** Unique county options for Community search (Category → County → City → State). */
export const COMMUNITY_COUNTY_OPTIONS = Array.from(
  new Map(
    COMMUNITY_MARKET_SEEDS.map((seed) => [
      `${seed.county_name}|${seed.state}`,
      { county: seed.county_name, state: seed.state as string },
    ]),
  ).values(),
).sort((a, b) =>
  a.state === b.state
    ? a.county.localeCompare(b.county)
    : a.state.localeCompare(b.state),
);
