import { router, type Href } from 'expo-router';
import type { ReactNode } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';

import SitGuruLogo from '@/components/SitGuruLogo';
import SitGuruScreen from '@/components/SitGuruScreen';
import { SitGuruColors } from '@/constants/colors';

type Status = 'Not started' | 'Future wiring' | 'Blocker';
type Action = { label: string; href?: Href; placeholder?: string };
type Strategy = { title: string; priority: string; why: string; status: Status; action?: Action };
type Phase = { n: number; title: string; route: string; data: string; risk: string; done: string; status: Status };
type Detail = { title: string; items: string[]; routes?: string[]; notes?: string[]; actions?: Action[] };

const href = (path: string) => path as Href;
const existingRoutes = new Set(['/backend-readiness','/schema-readiness','/auth-readiness','/release-readiness','/qa-test-center','/admin-operations','/account','/support','/notifications','/login','/signup','/role-selection','/pet-passports','/guru-pricing','/booking-details','/payments','/request-booking','/pawreport-live','/guru-live-walk','/guru-profile','/guru-dashboard','/pet-parent-dashboard','/ambassador-dashboard','/conversation','/guru-requests']);

function placeholder(label: string) {
  Alert.alert('Real Wiring Start Plan placeholder', `${label} is a safe visual-only planning action. No backend, auth, SQL, Stripe, GPS, storage, push notification, native API, or production wiring is added here.`);
}
function openAction(action: Action) { action.href && existingRoutes.has(String(action.href)) ? router.push(action.href) : placeholder(action.placeholder ?? action.label); }

const strategy: Strategy[] = [
  { title: 'Start with Auth', priority: '1', why: 'Every protected feature needs a known signed-in identity before real data can be trusted.', status: 'Blocker', action: { label: 'Auth Readiness', href: href('/auth-readiness') } },
  { title: 'Then Profiles', priority: '2', why: 'Profiles give each account display, contact, onboarding, and completion state.', status: 'Blocker', action: { label: 'Account', href: href('/account') } },
  { title: 'Then Roles', priority: '3', why: 'Pet Parent, Guru, Ambassador, and future Admin access must be loaded before routing.', status: 'Blocker', action: { label: 'Role Selection', href: href('/role-selection') } },
  { title: 'Then Pet Passports', priority: '4', why: 'Pet ownership and care notes unlock safe booking requests.', status: 'Future wiring', action: { label: 'Pet Passports', href: href('/pet-passports') } },
  { title: 'Then Guru Profiles', priority: '5', why: 'Guru service areas, services, and visibility power Find Care and booking decisions.', status: 'Future wiring', action: { label: 'Guru Profile', href: href('/guru-profile') } },
  { title: 'Then Messaging', priority: '6', why: 'Participant-only conversations need identity, roles, and booking context.', status: 'Future wiring', action: { label: 'Conversation', href: href('/conversation') } },
  { title: 'Then Booking Requests', priority: '7', why: 'Requests connect Pet Parent, pet, Guru, service, date, notes, and estimate.', status: 'Future wiring', action: { label: 'Booking Request', href: href('/request-booking') } },
  { title: 'Then Booking Details', priority: '8', why: 'Accepted bookings need status history, payments, messages, and care hubs.', status: 'Future wiring', action: { label: 'Booking Details', href: href('/booking-details') } },
  { title: 'Then PawReport Live', priority: '9', why: 'Live care depends on accepted bookings and participant-only access.', status: 'Future wiring', action: { label: 'PawReport Live', href: href('/pawreport-live') } },
  { title: 'Then Payments', priority: '10', why: 'Checkout should happen only after Guru acceptance and safe booking ownership.', status: 'Future wiring', action: { label: 'Payments', href: href('/payments') } },
  { title: 'Then Notifications', priority: '11', why: 'Notification records should reflect real booking, message, payment, and support events.', status: 'Future wiring', action: { label: 'Notifications', href: href('/notifications') } },
  { title: 'Then Admin Operations', priority: '12', why: 'Admin visibility requires server-side role checks and audit logs.', status: 'Future wiring', action: { label: 'Admin Operations', href: href('/admin-operations') } },
];

const phaseTitles = ['Supabase environment check','Auth session provider','Profile bootstrap','user_roles loading','Role selection routing','Protected dashboard shell','Pet Passport CRUD','Guru profile and service area CRUD','Guru pricing and availability saves','Conversations/messages','Booking request creation','Guru request review','Booking status events','PawReport visit sessions','Live location points','Visit updates and photos','Notifications','Stripe Checkout after Guru accepts','Stripe Connect payouts','Admin operations and audit logs','QA and release hardening'];
const phases: Phase[] = phaseTitles.map((title, i) => ({ n: i + 1, title, route: ['/backend-readiness','/auth-readiness','/account','/role-selection','/role-selection','/pet-parent-dashboard, /guru-dashboard','/pet-passports','/guru-profile','/guru-pricing','/conversation','/request-booking','/guru-requests','/booking-details','/pawreport-live, /guru-live-walk','/pawreport-live','/pawreport-live','/notifications','/payments','/payments','/admin-operations','/qa-test-center, /release-readiness'][i], data: ['Supabase URL, anon key, mobile env policy','auth session, auth user','profiles','user_roles','selected role + completion flags','session + role shell','pet profiles and notes','guru profiles, service areas','pricing rules, availability','conversations, messages','booking request records','request status and Guru decision','booking status events','visit session records','location point records','visit updates and future photo refs','notification records','payment records','payout records','admin notes, audit logs','QA checklist and release blockers'][i], risk: i < 6 ? 'Identity or role mistakes can expose protected screens.' : i < 17 ? 'Feature data must stay scoped to owners and booking participants.' : 'Financial, admin, or release work must not begin before security is ready.', done: i < 6 ? 'Users land in the correct safe visual shell with no broken route assumptions.' : i < 17 ? 'CRUD/realtime design is scoped, testable, and protected by future RLS.' : 'Sensitive flows have server-side controls, auditability, and QA coverage.', status: i < 6 ? 'Blocker' : 'Future wiring' }));

const details: Detail[] = [
  { title: 'Phase 1 detail: Supabase environment check', items: ['Confirm Supabase URL','Confirm anon key','Confirm mobile env strategy','Confirm no service role key in mobile client','Confirm project matches website backend','Confirm local development environment','Confirm staging/prod distinction future','Confirm error handling strategy'], actions: [{ label: 'Backend Readiness', href: href('/backend-readiness') }, { label: 'Schema Readiness', href: href('/schema-readiness') }, { label: 'Auth Readiness', href: href('/auth-readiness') }] },
  { title: 'Phase 2 detail: Auth session provider', items: ['Create Supabase client for mobile','Add session provider','Load current session','Subscribe to auth state changes','Handle sign out','Handle expired session','Handle loading screen','Protect signed-in screens','Keep Find Care public','Keep signup/login visual until real auth wiring starts'], notes: ['Do not block public Find Care.','Do not force signup before searching.','Only require login for messages, booking requests, payment, dashboard, and account features.'] },
  { title: 'Phase 3 detail: Profile bootstrap', items: ['After signup, create profile row','Store display name','Store email','Store phone placeholder later','Store city/state/ZIP later','Store avatar URL later','Store onboarding completion flags','Prevent duplicate profiles','Handle incomplete profiles'], routes: ['/signup','/login','/account','/role-selection'] },
  { title: 'Phase 4 detail: Role access and role switching', items: ['Load user_roles','Support Pet Parent','Support Guru','Support Ambassador','Support multiple roles','Future admin role','Redirect to role-selection if multiple roles','Redirect to role setup if incomplete','Keep role switching simple'], routes: ['/role-selection','/pet-parent-dashboard','/guru-dashboard','/ambassador-dashboard','/account'] },
  { title: 'Phase 5 detail: Pet Parent foundation', items: ['Pet Passports CRUD','Photo upload later','Feeding notes','Walk/potty notes','Medication/allergy notes','Behavior/comfort notes','Emergency/vet notes','Access/handoff notes','Pet ownership RLS'], routes: ['/pet-passports','/request-booking','/booking-details'] },
  { title: 'Phase 6 detail: Guru foundation', items: ['Guru profile CRUD','Service area','ZIP codes','Services offered','Pricing calendar','Availability','Profile visibility','Payout readiness placeholder','Guru ownership RLS'], routes: ['/guru-profile','/guru-dashboard','/guru-pricing','/guru-requests if present'] },
  { title: 'Phase 7 detail: Messaging foundation', items: ['conversations table','messages table','participants','realtime subscription','read/unread status','message ownership','support/admin visibility later','no cross-user data leaks'], routes: ['/conversation','/notifications','/booking-details'] },
  { title: 'Phase 8 detail: Booking foundation', items: ['Create booking request','Attach pet','Attach Guru','Attach service','Attach date/time','Attach care notes','Estimate pricing','Guru accept/decline','Booking status events','Payment not charged until Guru accepts'], routes: ['/request-booking','/booking-details','/guru-requests if present','/notifications','/payments if present'] },
  { title: 'Phase 9 detail: PawReport Live foundation', items: ['Visit session start','Visit session pause/resume','Visit session end','Location write only during active care','Pet Parent realtime read','Guru update writes','Timeline updates','Photo updates later','Final PawReport summary','Privacy and RLS for participants only'], routes: ['/pawreport-live','/guru-live-walk','/booking-details'] },
  { title: 'Phase 10 detail: Payments and payouts', items: ['Stripe Checkout after Guru accepts','No charge before acceptance','Payment records','Promo/PawPerks credits','Tips after completed care','Refund/adjustment support','Stripe Connect for Guru payouts','Payout records','Ambassador rewards later','Webhooks server-side later'], routes: ['/payments','/booking-details','/request-booking','/guru-dashboard','/ambassador-dashboard'] },
  { title: 'Phase 11 detail: Notifications', items: ['App notification records','Booking status alerts','Message alerts','PawReport Live alerts','Payment/payout alerts','Support alerts','Referral/PawPerks alerts','Push notifications later','Notification preferences'], routes: ['/notifications','/account','/booking-details','/pawreport-live','/payments'] },
  { title: 'Phase 12 detail: Admin operations', items: ['Admin role check','Active bookings','Live walks','Support queue','Safety flags','Payment/payout alerts','User management','Audit logs','Admin notes','No admin data in normal user role'], routes: ['/admin-operations','/support','/notifications','/payments','/booking-details'] },
];

const security = ['RLS before production','No service role key in mobile','Role checks server-side','User-owned data protected','Booking participants only','Admin-only operations protected','Payment data protected','Support data protected','Live location protected','Audit logs admin-only'];
const firstSteps = ['Step 1: mobile Supabase client','Step 2: auth provider','Step 3: login/signup real auth','Step 4: profile bootstrap','Step 5: user_roles load','Step 6: role-selection routing','Step 7: protect dashboards'];
const doNotStart = ['Do not start with real Stripe first','Do not start with live GPS first','Do not start with push notifications first','Do not start with admin operations first','Do not start with image uploads first','Do not start with reviews first'];
const quickActions: Action[] = [{ label: 'Auth Readiness', href: href('/auth-readiness') }, { label: 'Schema Readiness', href: href('/schema-readiness') }, { label: 'Backend Readiness', href: href('/backend-readiness') }, { label: 'Release Readiness', href: href('/release-readiness') }, { label: 'QA Test Center', href: href('/qa-test-center') }, { label: 'Account', href: href('/account') }, { label: 'Login', href: href('/login') }, { label: 'Signup', href: href('/signup') }, { label: 'Role Selection', href: href('/role-selection') }, { label: 'Pet Passports', href: href('/pet-passports') }, { label: 'Guru Pricing', href: href('/guru-pricing') }, { label: 'Booking Details', href: href('/booking-details') }, { label: 'Payments', href: href('/payments') }, { label: 'Support', href: href('/support') }];

export default function WiringStartPlanScreen() { return <SitGuruScreen scroll center={false} maxWidth={920}><View style={styles.page}>
  <View style={styles.topBar}><Pressable accessibilityRole="button" onPress={() => router.push(existingRoutes.has('/backend-readiness') ? href('/backend-readiness') : href('/account'))} style={styles.backButton}><Text style={styles.backButtonText}>← Back to Backend Readiness</Text></Pressable><SitGuruLogo size="small" variant="symbol" /></View>
  <View style={styles.hero}><Text style={styles.eyebrow}>Internal implementation roadmap</Text><Text style={styles.title}>Real Wiring Start Plan</Text><Text style={styles.subtitle}>Turn the visual SitGuru mobile app into a real app by wiring auth, roles, profiles, Pet Passports, bookings, messages, PawReport Live, payments, and notifications in the safest order.</Text><Text style={styles.notice}>Internal implementation roadmap only. No real backend, auth, SQL, Stripe, GPS, or push notification logic is added here.</Text></View>
  <Section title="Wiring strategy summary cards" eyebrow="Safe order"><View style={styles.grid}>{strategy.map((item) => <View key={item.title} style={styles.summaryCard}><Text style={styles.priority}>Priority {item.priority}</Text><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.body}>Why it matters: {item.why}</Text><Text style={[styles.badge, item.status === 'Blocker' && styles.badgeBlocker]}>{item.status}</Text>{item.action ? <Button action={item.action} /> : null}</View>)}</View></Section>
  <Section title="Recommended wiring order" eyebrow="Numbered phases">{phases.map((p) => <View key={p.n} style={styles.phaseCard}><View style={styles.cardHeader}><Text style={styles.phaseTitle}>{p.n}. {p.title}</Text><Text style={[styles.badge, p.status === 'Blocker' && styles.badgeBlocker]}>{p.status}</Text></View><Text style={styles.meta}>Route affected: {p.route}</Text><Text style={styles.meta}>Data needed: {p.data}</Text><Text style={styles.body}>Risk: {p.risk}</Text><Text style={styles.body}>Done when: {p.done}</Text></View>)}</Section>
  {details.map((detail) => <DetailCard key={detail.title} detail={detail} />)}
  <ListCard title="RLS and security blocker card" eyebrow="Production blocker" items={security} danger />
  <Section title="First real implementation should be Auth + Profile + Roles" eyebrow="Recommendation"><Text style={styles.body}>Do not start with payments, GPS, or realtime. Wire login/session, profile bootstrap, and user_roles first so every future feature has a safe identity foundation.</Text><View style={styles.grid}>{firstSteps.map((item) => <Text key={item} style={styles.checkItem}>□ {item}</Text>)}</View></Section>
  <Section title="Do not start with" eyebrow="Avoid risky sequencing"><View style={styles.grid}>{doNotStart.map((item) => <Text key={item} style={styles.dangerItem}>• {item}</Text>)}</View><Text style={styles.noticeLight}>Each depends on identity, roles, ownership, and safe access rules.</Text></Section>
  <Section title="Quick actions" eyebrow="Internal routes"><View style={styles.actions}>{quickActions.map((action) => <Button key={action.label} action={action} />)}</View></Section>
  <View style={styles.bottomDockSpacer} /></View><View style={styles.bottomDock}>{([{ label: 'Account', href: href('/account') }, { label: 'Auth', href: href('/auth-readiness') }, { label: 'Schema', href: href('/schema-readiness') }, { label: 'QA', href: href('/qa-test-center') }] satisfies Action[]).map((action) => <Pressable key={action.label} accessibilityRole="button" onPress={() => openAction(action)} style={styles.dockButton}><Text style={styles.dockButtonText}>{action.label}</Text></Pressable>)}</View></SitGuruScreen>; }

function Section({ title, eyebrow, children }: { title: string; eyebrow?: string; children: ReactNode }) { return <View style={styles.section}>{eyebrow ? <Text style={styles.eyebrowGreen}>{eyebrow}</Text> : null}<Text style={styles.sectionTitle}>{title}</Text>{children}</View>; }
function Button({ action }: { action: Action }) { return <Pressable accessibilityRole="button" onPress={() => openAction(action)} style={styles.button}><Text style={styles.buttonText}>{action.label}</Text></Pressable>; }
function ListCard({ title, eyebrow, items, danger = false }: { title: string; eyebrow: string; items: string[]; danger?: boolean }) { return <Section title={title} eyebrow={eyebrow}><View style={styles.grid}>{items.map((item) => <Pressable key={item} accessibilityRole="button" onPress={() => placeholder(item)} style={[styles.listItem, danger && styles.listDanger]}><Text style={styles.checkText}>□ {item}</Text></Pressable>)}</View></Section>; }
function DetailCard({ detail }: { detail: Detail }) { return <Section title={detail.title} eyebrow="Future tasks"><View style={styles.grid}>{detail.items.map((item) => <Pressable key={item} accessibilityRole="button" onPress={() => placeholder(item)} style={styles.listItem}><Text style={styles.checkText}>□ {item}</Text></Pressable>)}</View>{detail.routes ? <Text style={styles.meta}>Routes affected: {detail.routes.join(', ')}</Text> : null}{detail.notes?.map((note) => <Text key={note} style={styles.noticeLight}>{note}</Text>)}{detail.actions ? <View style={styles.actions}>{detail.actions.map((action) => <Button key={action.label} action={action} />)}</View> : null}</Section>; }

const styles = StyleSheet.create({
  page: { gap: 16, paddingBottom: 8 }, topBar: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, backButton: { backgroundColor: SitGuruColors.surface, borderColor: SitGuruColors.border, borderRadius: 999, borderWidth: 1, paddingHorizontal: 14, paddingVertical: 10 }, backButtonText: { color: SitGuruColors.text, fontSize: 14, fontWeight: '900' },
  hero: { backgroundColor: SitGuruColors.primaryDark, borderRadius: 30, gap: 10, padding: 22 }, eyebrow: { color: '#C9F26D', fontSize: 12, fontWeight: '900', letterSpacing: 0.8, textTransform: 'uppercase' }, title: { color: '#FFFFFF', fontSize: 36, fontWeight: '900', letterSpacing: -1, lineHeight: 40 }, subtitle: { color: '#DCEFE2', fontSize: 15, fontWeight: '700', lineHeight: 22 }, notice: { backgroundColor: 'rgba(255,255,255,0.12)', borderColor: 'rgba(255,255,255,0.22)', borderRadius: 18, borderWidth: 1, color: '#FFFFFF', fontSize: 13, fontWeight: '900', lineHeight: 19, padding: 12 },
  section: { backgroundColor: SitGuruColors.surface, borderColor: SitGuruColors.border, borderRadius: 28, borderWidth: 1, gap: 12, padding: 18 }, eyebrowGreen: { color: SitGuruColors.primary, fontSize: 12, fontWeight: '900', letterSpacing: 0.7, textTransform: 'uppercase' }, sectionTitle: { color: SitGuruColors.text, fontSize: 23, fontWeight: '900', letterSpacing: -0.4 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  summaryCard: { backgroundColor: SitGuruColors.background, borderColor: SitGuruColors.border, borderRadius: 22, borderWidth: 1, flexBasis: 245, flexGrow: 1, gap: 8, padding: 14 }, priority: { color: SitGuruColors.primary, fontSize: 12, fontWeight: '900', textTransform: 'uppercase' }, cardTitle: { color: SitGuruColors.text, fontSize: 17, fontWeight: '900' }, body: { color: SitGuruColors.textMuted, fontSize: 14, fontWeight: '700', lineHeight: 21 }, meta: { color: SitGuruColors.textSoft, fontSize: 12, fontWeight: '900', lineHeight: 18 },
  phaseCard: { backgroundColor: SitGuruColors.background, borderColor: SitGuruColors.border, borderRadius: 20, borderWidth: 1, gap: 7, padding: 14 }, cardHeader: { alignItems: 'flex-start', flexDirection: 'row', flexWrap: 'wrap', gap: 10, justifyContent: 'space-between' }, phaseTitle: { color: SitGuruColors.text, flex: 1, fontSize: 17, fontWeight: '900', minWidth: 220 }, badge: { alignSelf: 'flex-start', backgroundColor: SitGuruColors.surfaceSoft, borderRadius: 999, color: SitGuruColors.primary, fontSize: 12, fontWeight: '900', overflow: 'hidden', paddingHorizontal: 10, paddingVertical: 6 }, badgeBlocker: { backgroundColor: '#FFF1F2', color: SitGuruColors.danger },
  actions: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, button: { alignItems: 'center', backgroundColor: SitGuruColors.primary, borderRadius: 999, flexGrow: 1, justifyContent: 'center', minHeight: 48, paddingHorizontal: 16 }, buttonText: { color: '#FFFFFF', fontSize: 14, fontWeight: '900' }, listItem: { backgroundColor: SitGuruColors.background, borderColor: SitGuruColors.border, borderRadius: 16, borderWidth: 1, flexBasis: 240, flexGrow: 1, padding: 12 }, listDanger: { backgroundColor: '#FFF7ED', borderColor: '#FED7AA' }, checkItem: { backgroundColor: SitGuruColors.background, borderColor: SitGuruColors.border, borderRadius: 16, borderWidth: 1, color: SitGuruColors.text, flexBasis: 240, flexGrow: 1, fontSize: 14, fontWeight: '800', overflow: 'hidden', padding: 12 }, dangerItem: { backgroundColor: '#FFF7ED', borderColor: '#FED7AA', borderRadius: 16, borderWidth: 1, color: SitGuruColors.text, flexBasis: 240, flexGrow: 1, fontSize: 14, fontWeight: '900', overflow: 'hidden', padding: 12 }, checkText: { color: SitGuruColors.text, fontSize: 14, fontWeight: '800', lineHeight: 20 }, noticeLight: { backgroundColor: '#F3FAED', borderColor: '#DDEFD2', borderRadius: 18, borderWidth: 1, color: SitGuruColors.text, fontSize: 14, fontWeight: '800', lineHeight: 20, padding: 12 },
  bottomDockSpacer: { height: 88 }, bottomDock: { alignItems: 'center', alignSelf: 'center', backgroundColor: 'rgba(255,255,255,0.96)', borderColor: SitGuruColors.border, borderRadius: 999, borderWidth: 1, bottom: 16, elevation: 8, flexDirection: 'row', gap: 6, left: 16, padding: 8, position: 'absolute', right: 16 }, dockButton: { alignItems: 'center', backgroundColor: SitGuruColors.surfaceSoft, borderRadius: 999, flex: 1, justifyContent: 'center', minHeight: 48, paddingHorizontal: 8 }, dockButtonText: { color: SitGuruColors.primary, fontSize: 12, fontWeight: '900' },
});
