export const dogBreeds = [
  "Affenpinscher",
  "Afghan Hound",
  "Airedale Terrier",
  "Akita",
  "Alaskan Klee Kai",
  "Alaskan Malamute",
  "American Bulldog",
  "American Bully",
  "American Cocker Spaniel",
  "American English Coonhound",
  "American Eskimo Dog",
  "American Foxhound",
  "American Hairless Terrier",
  "American Leopard Hound",
  "American Pit Bull Terrier",
  "American Staffordshire Terrier",
  "American Water Spaniel",
  "Anatolian Shepherd Dog",
  "Appenzeller Sennenhund",
  "Australian Cattle Dog",
  "Australian Kelpie",
  "Australian Labradoodle",
  "Australian Shepherd",
  "Australian Stumpy Tail Cattle Dog",
  "Australian Terrier",
  "Azawakh",
  "Barbet",
  "Basenji",
  "Basset Fauve de Bretagne",
  "Basset Hound",
  "Bavarian Mountain Scent Hound",
  "Beagle",
  "Bearded Collie",
  "Beauceron",
  "Bedlington Terrier",
  "Belgian Laekenois",
  "Belgian Malinois",
  "Belgian Sheepdog",
  "Belgian Tervuren",
  "Bernedoodle",
  "Bernese Mountain Dog",
  "Bichon Frise",
  "Biewer Terrier",
  "Black and Tan Coonhound",
  "Black Russian Terrier",
  "Bloodhound",
  "Bluetick Coonhound",
  "Boerboel",
  "Bohemian Shepherd",
  "Bolognese",
  "Border Collie",
  "Border Terrier",
  "Borzoi",
  "Boston Terrier",
  "Bouvier des Flandres",
  "Boxer",
  "Boykin Spaniel",
  "Bracco Italiano",
  "Braque du Bourbonnais",
  "Briard",
  "Brittany",
  "Broholmer",
  "Brussels Griffon",
  "Bull Terrier",
  "Bulldog",
  "Bullmastiff",
  "Cairn Terrier",
  "Canaan Dog",
  "Cane Corso",
  "Cardigan Welsh Corgi",
  "Carolina Dog",
  "Catahoula Leopard Dog",
  "Caucasian Shepherd Dog",
  "Cavalier King Charles Spaniel",
  "Cavapoo",
  "Central Asian Shepherd Dog",
  "Cesky Terrier",
  "Chesapeake Bay Retriever",
  "Chihuahua",
  "Chinese Crested",
  "Chinese Shar-Pei",
  "Chinook",
  "Chiweenie",
  "Chow Chow",
  "Cirneco dell'Etna",
  "Clumber Spaniel",
  "Cockapoo",
  "Cocker Spaniel",
  "Collie",
  "Coton de Tulear",
  "Curly-Coated Retriever",
  "Dachshund",
  "Dalmatian",
  "Dandie Dinmont Terrier",
  "Danish-Swedish Farmdog",
  "Doberman Pinscher",
  "Dogo Argentino",
  "Dogue de Bordeaux",
  "Dutch Shepherd",
  "English Cocker Spaniel",
  "English Foxhound",
  "English Setter",
  "English Springer Spaniel",
  "English Toy Spaniel",
  "Entlebucher Mountain Dog",
  "Estrela Mountain Dog",
  "Eurasier",
  "Field Spaniel",
  "Finnish Lapphund",
  "Finnish Spitz",
  "Flat-Coated Retriever",
  "French Bulldog",
  "French Spaniel",
  "German Longhaired Pointer",
  "German Pinscher",
  "German Shepherd",
  "German Shepherd Dog",
  "German Shorthaired Pointer",
  "German Spitz",
  "German Wirehaired Pointer",
  "Giant Schnauzer",
  "Glen of Imaal Terrier",
  "Golden Retriever",
  "Goldendoodle",
  "Gordon Setter",
  "Grand Basset Griffon Vendéen",
  "Great Dane",
  "Great Pyrenees",
  "Greater Swiss Mountain Dog",
  "Greyhound",
  "Hamiltonstovare",
  "Hanoverian Scenthound",
  "Harrier",
  "Havanese",
  "Hokkaido",
  "Hovawart",
  "Ibizan Hound",
  "Icelandic Sheepdog",
  "Irish Red and White Setter",
  "Irish Setter",
  "Irish Terrier",
  "Irish Water Spaniel",
  "Irish Wolfhound",
  "Italian Greyhound",
  "Jack Russell Terrier",
  "Japanese Akitainu",
  "Japanese Chin",
  "Japanese Spitz",
  "Japanese Terrier",
  "Jindo",
  "Kai Ken",
  "Karelian Bear Dog",
  "Keeshond",
  "Kerry Blue Terrier",
  "Kishu Ken",
  "Komondor",
  "Kooikerhondje",
  "Kromfohrlander",
  "Kuvasz",
  "Labradoodle",
  "Labrador Retriever",
  "Lagotto Romagnolo",
  "Lakeland Terrier",
  "Lancashire Heeler",
  "Lapponian Herder",
  "Leonberger",
  "Lhasa Apso",
  "Löwchen",
  "Maltese",
  "Manchester Terrier",
  "Mastiff",
  "Miniature American Shepherd",
  "Miniature Bull Terrier",
  "Miniature Pinscher",
  "Miniature Poodle",
  "Miniature Schnauzer",
  "Mountain Cur",
  "Mudi",
  "Neapolitan Mastiff",
  "Newfoundland",
  "Norfolk Terrier",
  "Norrbottenspets",
  "Norwegian Buhund",
  "Norwegian Elkhound",
  "Norwegian Lundehund",
  "Norwich Terrier",
  "Nova Scotia Duck Tolling Retriever",
  "Old English Sheepdog",
  "Otterhound",
  "Papillon",
  "Parson Russell Terrier",
  "Patterdale Terrier",
  "Pekingese",
  "Pembroke Welsh Corgi",
  "Perro de Presa Canario",
  "Peruvian Inca Orchid",
  "Petit Basset Griffon Vendéen",
  "Pharaoh Hound",
  "Pit Bull Mix",
  "Plott Hound",
  "Pointer",
  "Polish Lowland Sheepdog",
  "Pomeranian",
  "Pomsky",
  "Poodle",
  "Portuguese Podengo",
  "Portuguese Podengo Pequeno",
  "Portuguese Pointer",
  "Portuguese Sheepdog",
  "Portuguese Water Dog",
  "Pug",
  "Puggle",
  "Puli",
  "Pumi",
  "Pyrenean Mastiff",
  "Pyrenean Shepherd",
  "Rat Terrier",
  "Redbone Coonhound",
  "Rhodesian Ridgeback",
  "Rottweiler",
  "Russian Toy",
  "Russian Tsvetnaya Bolonka",
  "Saint Bernard",
  "Saluki",
  "Samoyed",
  "Schapendoes",
  "Schipperke",
  "Schnauzer",
  "Scottish Deerhound",
  "Scottish Terrier",
  "Sealyham Terrier",
  "Segugio Italiano",
  "Shetland Sheepdog",
  "Shiba Inu",
  "Shih Tzu",
  "Shih-Poo",
  "Shikoku",
  "Siberian Husky",
  "Silky Terrier",
  "Skye Terrier",
  "Sloughi",
  "Small Munsterlander",
  "Soft Coated Wheaten Terrier",
  "Spanish Mastiff",
  "Spanish Water Dog",
  "Spinone Italiano",
  "Staffordshire Bull Terrier",
  "Standard Poodle",
  "Standard Schnauzer",
  "Sussex Spaniel",
  "Swedish Lapphund",
  "Swedish Vallhund",
  "Taiwan Dog",
  "Teddy Roosevelt Terrier",
  "Thai Ridgeback",
  "Tibetan Mastiff",
  "Tibetan Spaniel",
  "Tibetan Terrier",
  "Tornjak",
  "Tosa",
  "Toy Fox Terrier",
  "Toy Poodle",
  "Transylvanian Hound",
  "Treeing Tennessee Brindle",
  "Treeing Walker Coonhound",
  "Vizsla",
  "Volpino Italiano",
  "Weimaraner",
  "Welsh Springer Spaniel",
  "Welsh Terrier",
  "West Highland White Terrier",
  "Whippet",
  "Wire Fox Terrier",
  "Wirehaired Pointing Griffon",
  "Wirehaired Vizsla",
  "Working Kelpie",
  "Xoloitzcuintli",
  "Yorkipoo",
  "Yorkshire Terrier",
  "Mixed Breed",
  "Rescue Mix",
  "Unknown",
  "Other",
] as const;

export const catBreeds = [
  "Abyssinian",
  "Aegean",
  "American Bobtail",
  "American Bobtail Longhair",
  "American Bobtail Shorthair",
  "American Curl",
  "American Curl Longhair",
  "American Curl Shorthair",
  "American Ringtail",
  "American Shorthair",
  "American Wirehair",
  "Aphrodite",
  "Arabian Mau",
  "Asian",
  "Asian Longhair",
  "Australian Mist",
  "Balinese",
  "Bambino",
  "Bengal",
  "Birman",
  "Bombay",
  "Brazilian Shorthair",
  "British Longhair",
  "British Shorthair",
  "Burmese",
  "Burmilla",
  "California Spangled",
  "Chantilly-Tiffany",
  "Chartreux",
  "Chausie",
  "Colorpoint Shorthair",
  "Cornish Rex",
  "Cymric",
  "Devon Rex",
  "Donskoy",
  "Domestic Longhair",
  "Domestic Medium Hair",
  "Domestic Shorthair",
  "Dragon Li",
  "Dwelf",
  "Egyptian Mau",
  "European Burmese",
  "European Shorthair",
  "Exotic Longhair",
  "Exotic Shorthair",
  "Foldex",
  "German Rex",
  "Havana Brown",
  "Highlander",
  "Himalayan",
  "Japanese Bobtail",
  "Japanese Bobtail Longhair",
  "Japanese Bobtail Shorthair",
  "Javanese",
  "Khao Manee",
  "Kinkalow",
  "Korat",
  "Korean Bobtail",
  "Kurilian Bobtail",
  "Kurilian Bobtail Longhair",
  "Kurilian Bobtail Shorthair",
  "LaPerm",
  "LaPerm Longhair",
  "LaPerm Shorthair",
  "Lykoi",
  "Maine Coon",
  "Manx",
  "Mekong Bobtail",
  "Minskin",
  "Minuet",
  "Minuet Longhair",
  "Minuet Shorthair",
  "Munchkin",
  "Munchkin Longhair",
  "Munchkin Shorthair",
  "Nebelung",
  "Norwegian Forest Cat",
  "Ocicat",
  "Ojos Azules",
  "Oriental Longhair",
  "Oriental Shorthair",
  "Persian",
  "Peterbald",
  "Pixiebob",
  "RagaMuffin",
  "Ragdoll",
  "Russian Blue",
  "Savannah",
  "Scottish Fold",
  "Scottish Fold Longhair",
  "Scottish Fold Shorthair",
  "Scottish Straight",
  "Selkirk Rex",
  "Serengeti",
  "Siamese",
  "Siberian",
  "Singapura",
  "Snowshoe",
  "Sokoke",
  "Somali",
  "Sphynx",
  "Thai",
  "Tonkinese",
  "Toyger",
  "Turkish Angora",
  "Turkish Van",
  "Ukrainian Levkoy",
  "York Chocolate",
  "Calico",
  "Tabby",
  "Tortoiseshell",
  "Tuxedo",
  "Mixed Breed",
  "Rescue Mix",
  "Unknown",
  "Other",
] as const;

export const otherPetTypes = [
  "Bird",
  "Rabbit",
  "Guinea Pig",
  "Hamster",
  "Gerbil",
  "Ferret",
  "Reptile",
  "Turtle",
  "Fish",
  "Horse",
  "Farm Animal",
  "Small Animal",
  "Other",
] as const;

export const petBreedOptionsByType = {
  dog: dogBreeds,
  cat: catBreeds,
} as const;

export type NormalizedPetType = "dog" | "cat" | "other";

export type DogBreed = (typeof dogBreeds)[number];
export type CatBreed = (typeof catBreeds)[number];
export type OtherPetType = (typeof otherPetTypes)[number];
export type PetBreed = DogBreed | CatBreed | string;

export function normalizePetTypeForBreedOptions(
  value: string | null | undefined,
): NormalizedPetType {
  const normalized = String(value || "").trim().toLowerCase();

  if (
    normalized === "dog" ||
    normalized === "dogs" ||
    normalized === "puppy" ||
    normalized === "puppies" ||
    normalized === "canine"
  ) {
    return "dog";
  }

  if (
    normalized === "cat" ||
    normalized === "cats" ||
    normalized === "kitten" ||
    normalized === "kittens" ||
    normalized === "feline"
  ) {
    return "cat";
  }

  return "other";
}

export function getPetBreedOptions(
  petType: string | null | undefined,
): readonly string[] {
  const normalizedType = normalizePetTypeForBreedOptions(petType);

  if (normalizedType === "dog") {
    return dogBreeds;
  }

  if (normalizedType === "cat") {
    return catBreeds;
  }

  return [] as const;
}

export function filterPetBreedOptions(params: {
  petType: string | null | undefined;
  query: string;
  limit?: number;
}) {
  const options = getPetBreedOptions(params.petType);
  const normalizedQuery = params.query.trim().toLowerCase();
  const limit = params.limit ?? 30;

  if (!normalizedQuery) {
    return options.slice(0, limit);
  }

  return options
    .filter((breed) => breed.toLowerCase().includes(normalizedQuery))
    .slice(0, limit);
}

export function isKnownPetBreed(params: {
  petType: string | null | undefined;
  breed: string | null | undefined;
}) {
  const normalizedBreed = String(params.breed || "").trim().toLowerCase();

  if (!normalizedBreed) {
    return false;
  }

  return getPetBreedOptions(params.petType).some(
    (breed) => breed.toLowerCase() === normalizedBreed,
  );
}