import type { GrowthCampaign, GrowthContent, GrowthHomeStats } from "@/lib/admin/growth/data";
import { INTERN_KPI_BASELINE_NOTE, type InternSafeKpiSnapshot } from "@/lib/internship/intern-kpis";
import type { InternPromoteEvent } from "@/lib/internship/intern-tools";
import type { InternDocumentationScene } from "@/lib/internship/documentation-mode";
import type {
  InternshipCampaign,
  InternshipContentItem,
  InternshipExperiment,
  InternshipMetric,
  InternshipMilestone,
  InternshipSmartGoal,
  InternshipTask,
  InternshipWeeklyReview,
  InternshipWorkAttachment,
  InternshipWorkComment,
  InternshipWorkspaceData,
  TaskStatus,
} from "@/lib/internship/types";

export const DOCUMENTATION_INTERN_ID = "doc-intern-taylor-morgan";
export const DOCUMENTATION_UNIVERSITY_ID = "doc-university-example";
export const DOCUMENTATION_COHORT_ID = "doc-cohort-spring-2027";
export const DOCUMENTATION_PROJECT_ID = "doc-project-philly-growth";
export const DOCUMENTATION_CAMPAIGN_ID = "doc-campaign-sg-sp27-pp-004";

const INTERN_ID = DOCUMENTATION_INTERN_ID;

function task(
  id: string,
  title: string,
  status: TaskStatus,
  extra: Partial<InternshipTask> = {},
): InternshipTask {
  return {
    id,
    internId: INTERN_ID,
    projectId: DOCUMENTATION_PROJECT_ID,
    title,
    dueOn: extra.dueOn ?? null,
    status,
    workUrl: extra.workUrl || "",
    businessObjective: extra.businessObjective || "",
    metricAffected: extra.metricAffected || "",
    studentNotes: extra.studentNotes || "",
    supervisorNotes: extra.supervisorNotes || "",
    supervisorApproved: status === "approved",
    approvedAt: status === "approved" ? "2026-09-04T15:00:00.000Z" : null,
    submittedAt:
      status === "submitted" || status === "revision_requested" || status === "approved"
        ? "2026-09-03T18:00:00.000Z"
        : null,
    employerLetter: extra.employerLetter || "",
    kpiTier: extra.kpiTier || "tier_1",
    outputVsTarget: extra.outputVsTarget ?? null,
    finalSection: extra.finalSection || "pet_parent_growth",
    weekNumber: extra.weekNumber ?? 5,
    campaignId: extra.campaignId || DOCUMENTATION_CAMPAIGN_ID,
    internReportedValue: extra.internReportedValue || "",
    verifiedValue: extra.verifiedValue || "",
  };
}

const TASKS: InternshipTask[] = [
  task("doc-task-01", "Map Greater Philadelphia Pet Parent demand", "approved", {
    dueOn: "2026-08-16",
    weekNumber: 1,
    finalSection: "market_analysis",
    workUrl: "https://example.edu/intern/market-map.pdf",
    businessObjective: "Define the assigned market before campaigns launch.",
    studentNotes: "Mapped ZIP clusters around Example University and nearby parks.",
  }),
  task("doc-task-02", "Lock Pet Parent registration baseline", "approved", {
    dueOn: "2026-08-20",
    weekNumber: 2,
    finalSection: "growth_strategy",
    internReportedValue: "20",
    verifiedValue: "20",
  }),
  task("doc-task-03", "Write Pet Parent and Guru personas", "approved", {
    dueOn: "2026-08-27",
    weekNumber: 3,
    finalSection: "audience_strategy",
  }),
  task("doc-task-04", "Draft content pillars and CTAs", "approved", {
    dueOn: "2026-08-30",
    weekNumber: 4,
    finalSection: "content_system",
  }),
  task("doc-task-05", "Build UTM sheet for SG-SP27-PP-004", "submitted", {
    dueOn: "2026-09-08",
    weekNumber: 5,
    finalSection: "campaign_system",
    workUrl: "https://example.edu/intern/utm-sheet.pdf",
    studentNotes: "Ready for SitGuru review. Tracking links use example UTM values only.",
  }),
  task("doc-task-06", "Weekend Pet Parent Instagram carousel", "in_progress", {
    dueOn: "2026-09-10",
    weekNumber: 5,
    finalSection: "content_system",
    studentNotes: "Draft captions done. Waiting on brand-safe photos.",
  }),
  task("doc-task-07", "Log first campaign experiment", "revision_requested", {
    dueOn: "2026-09-07",
    weekNumber: 5,
    finalSection: "pet_parent_growth",
    supervisorNotes:
      "Add the hypothesis, the exact CTA, and which tracking link you used before resubmitting.",
    studentNotes: "Posted once; need to attach the UTM evidence SitGuru requested.",
  }),
  task("doc-task-08", "Guru highlight reel for Find Care", "todo", {
    dueOn: "2026-09-14",
    weekNumber: 6,
    finalSection: "guru_growth",
  }),
  task("doc-task-09", "Community partner outreach list", "todo", {
    dueOn: "2026-09-18",
    weekNumber: 6,
    finalSection: "partner_growth",
  }),
  task("doc-task-10", "Landing-page CTA test plan", "todo", {
    dueOn: "2026-09-21",
    weekNumber: 7,
    finalSection: "conversion_optimization",
  }),
  task("doc-task-11", "Weekly attribution snapshot", "todo", {
    dueOn: "2026-09-25",
    weekNumber: 7,
    finalSection: "analytics_attribution",
  }),
  task("doc-task-12", "SOP: how to launch a SitGuru weekend campaign", "in_progress", {
    dueOn: "2026-10-02",
    weekNumber: 8,
    finalSection: "sop_handoff",
  }),
  task("doc-task-13", "Midpoint Business Growth Report draft", "todo", {
    dueOn: "2026-10-09",
    weekNumber: 8,
    finalSection: "business_growth_report",
  }),
  task("doc-task-14", "Portfolio case study outline", "todo", {
    dueOn: "2026-10-16",
    weekNumber: 9,
    finalSection: "portfolio_case_study",
  }),
  task("doc-task-15", "TikTok Find Care hook test", "submitted", {
    dueOn: "2026-09-11",
    weekNumber: 5,
    finalSection: "content_system",
    workUrl: "https://example.edu/intern/tiktok-hook.pdf",
  }),
  task("doc-task-16", "Facebook event share with tracking link", "todo", {
    dueOn: "2026-09-12",
    weekNumber: 5,
    finalSection: "campaign_system",
  }),
  task("doc-task-17", "YouTube Short: Rogue at the park (no real pets)", "todo", {
    dueOn: "2026-09-19",
    weekNumber: 6,
    finalSection: "content_system",
  }),
  task("doc-task-18", "Referral code placement on Example University Discord", "blocked", {
    dueOn: "2026-09-15",
    weekNumber: 5,
    finalSection: "campaign_system",
    studentNotes: "Waiting on campus club approval. No student emails stored here.",
  }),
  task("doc-task-19", "Compare verified vs reported Pet Parent signups", "in_progress", {
    dueOn: "2026-09-13",
    weekNumber: 5,
    finalSection: "analytics_attribution",
    internReportedValue: "12",
    verifiedValue: "9",
  }),
  task("doc-task-20", "Handoff notes for next intern", "todo", {
    dueOn: "2026-11-20",
    weekNumber: 14,
    finalSection: "sop_handoff",
  }),
  task("doc-task-21", "Final portfolio case study draft", "todo", {
    dueOn: "2026-12-04",
    weekNumber: 15,
    finalSection: "portfolio_case_study",
  }),
];

const CONTENT: InternshipContentItem[] = [
  {
    id: "doc-content-draft",
    internId: INTERN_ID,
    title: "Weekend walk CTA — Instagram draft",
    platform: "Instagram",
    draftUrl: "https://example.edu/intern/ig-weekend-draft.pdf",
    publishedUrl: "",
    status: "draft",
    dueOn: "2026-09-10",
    studentNotes:
      "Audience: Example University pet parents. Objective: drive Find Care signups. Campaign: SG-SP27-PP-004. CTA: Book on SitGuru. Tracking: utm_campaign=sg_sp27_pp_004.",
    supervisorNotes: "",
    supervisorApproved: false,
    submittedAt: null,
    employerLetter: "",
    kpiTier: "tier_2",
    outputVsTarget: null,
    finalSection: "content_system",
  },
  {
    id: "doc-content-submitted",
    internId: INTERN_ID,
    title: "Find Care carousel — submitted for review",
    platform: "Instagram",
    draftUrl: "https://example.edu/intern/ig-find-care.pdf",
    publishedUrl: "",
    status: "submitted",
    dueOn: "2026-09-09",
    studentNotes: "Submitted with UTM link. Waiting on SitGuru approval.",
    supervisorNotes: "",
    supervisorApproved: false,
    submittedAt: "2026-09-05T16:00:00.000Z",
    employerLetter: "",
    kpiTier: "tier_2",
    outputVsTarget: null,
    finalSection: "pet_parent_growth",
  },
  {
    id: "doc-content-revision",
    internId: INTERN_ID,
    title: "TikTok hook — changes requested",
    platform: "TikTok",
    draftUrl: "https://example.edu/intern/tiktok-hook.pdf",
    publishedUrl: "",
    status: "revision_requested",
    dueOn: "2026-09-08",
    studentNotes: "First cut used a generic park clip.",
    supervisorNotes: "Lead with the Find Care CTA and the tracking link in the caption.",
    supervisorApproved: false,
    submittedAt: "2026-09-04T14:00:00.000Z",
    employerLetter: "",
    kpiTier: "tier_3",
    outputVsTarget: null,
    finalSection: "content_system",
  },
  {
    id: "doc-content-approved",
    internId: INTERN_ID,
    title: "Facebook event share — approved",
    platform: "Facebook",
    draftUrl: "https://example.edu/intern/fb-event.pdf",
    publishedUrl: "",
    status: "approved",
    dueOn: "2026-09-12",
    studentNotes: "Approved copy. Scheduled for Friday.",
    supervisorNotes: "",
    supervisorApproved: true,
    submittedAt: "2026-09-02T12:00:00.000Z",
    employerLetter: "B",
    kpiTier: "tier_2",
    outputVsTarget: 0.8,
    finalSection: "campaign_system",
  },
  {
    id: "doc-content-scheduled",
    internId: INTERN_ID,
    title: "Stories reminder — scheduled",
    platform: "Instagram",
    draftUrl: "https://example.edu/intern/ig-stories.pdf",
    publishedUrl: "",
    status: "scheduled",
    dueOn: "2026-09-11",
    studentNotes: "Queued for Saturday morning.",
    supervisorNotes: "",
    supervisorApproved: true,
    submittedAt: "2026-09-03T12:00:00.000Z",
    employerLetter: "",
    kpiTier: "tier_3",
    outputVsTarget: null,
    finalSection: "campaign_system",
  },
  {
    id: "doc-content-published",
    internId: INTERN_ID,
    title: "Find Care weekend post — published",
    platform: "Instagram",
    draftUrl: "https://example.edu/intern/ig-published-draft.pdf",
    publishedUrl: "https://www.sitguru.com/search",
    status: "published",
    dueOn: "2026-09-05",
    studentNotes: "Published with SG-SP27-PP-004 tracking.",
    supervisorNotes: "",
    supervisorApproved: true,
    submittedAt: "2026-09-01T12:00:00.000Z",
    employerLetter: "B",
    kpiTier: "tier_1",
    outputVsTarget: 0.75,
    finalSection: "pet_parent_growth",
  },
];

const CAMPAIGNS: InternshipCampaign[] = [
  {
    id: DOCUMENTATION_CAMPAIGN_ID,
    internId: INTERN_ID,
    projectId: DOCUMENTATION_PROJECT_ID,
    name: "SG-SP27-PP-004 Spring Weekend Pet Parent Campaign",
    utmSource: "instagram",
    utmCampaign: "sg_sp27_pp_004",
    referralCode: "SG-SP27-PP-004",
    trackingUrl:
      "https://www.sitguru.com/search?utm_source=instagram&utm_medium=social&utm_campaign=sg_sp27_pp_004&utm_content=weekend_walk",
    objective:
      "Increase attributable Greater Philadelphia Pet Parent registrations from baseline 20 toward SMART target 40.",
    status: "active",
    primaryOwnerInternId: INTERN_ID,
    finalSection: "campaign_system",
  },
  {
    id: "doc-campaign-planning",
    internId: INTERN_ID,
    projectId: DOCUMENTATION_PROJECT_ID,
    name: "SG-SP27-GURU-001 Guru highlight series",
    utmSource: "tiktok",
    utmCampaign: "sg_sp27_guru_001",
    referralCode: "SG-SP27-GURU-001",
    trackingUrl:
      "https://www.sitguru.com/search?utm_source=tiktok&utm_medium=social&utm_campaign=sg_sp27_guru_001",
    objective: "Send Pet Parents to Find Care Guru profiles in the assigned market.",
    status: "planning",
    primaryOwnerInternId: INTERN_ID,
    finalSection: "guru_growth",
  },
  {
    id: "doc-campaign-completed",
    internId: INTERN_ID,
    projectId: DOCUMENTATION_PROJECT_ID,
    name: "SG-SP27-PP-001 Baseline awareness week",
    utmSource: "facebook",
    utmCampaign: "sg_sp27_pp_001",
    referralCode: "SG-SP27-PP-001",
    trackingUrl:
      "https://www.sitguru.com/search?utm_source=facebook&utm_medium=social&utm_campaign=sg_sp27_pp_001",
    objective: "Establish tracking before counting Pet Parent registrations.",
    status: "completed",
    primaryOwnerInternId: INTERN_ID,
    finalSection: "analytics_attribution",
  },
];

function metric(
  id: string,
  label: string,
  metricKey: string,
  value: number,
  extra: Partial<InternshipMetric>,
): InternshipMetric {
  return {
    id,
    internId: INTERN_ID,
    campaignId: DOCUMENTATION_CAMPAIGN_ID,
    projectId: DOCUMENTATION_PROJECT_ID,
    metricKey,
    label,
    valueNumeric: value,
    periodStart: extra.periodStart || "2026-08-09",
    periodEnd: extra.periodEnd || "2026-09-06",
    sourceSystem: extra.sourceSystem || "registration_records",
    sourceNote: extra.sourceNote || "",
    isVerified: Boolean(extra.isVerified),
    selfReported: extra.selfReported !== false,
    finalSection: extra.finalSection || "pet_parent_growth",
  };
}

const METRICS: InternshipMetric[] = [
  metric("doc-metric-baseline-pp", "Pet Parent baseline", "people.pet_parents", 20, {
    isVerified: true,
    selfReported: false,
    sourceNote: INTERN_KPI_BASELINE_NOTE,
    sourceSystem: "sitguru_admin",
    periodEnd: "2026-08-20",
  }),
  metric("doc-metric-baseline-gurus", "Guru baseline", "people.gurus", 8, {
    isVerified: true,
    selfReported: false,
    sourceNote: INTERN_KPI_BASELINE_NOTE,
    sourceSystem: "sitguru_admin",
    periodEnd: "2026-08-20",
  }),
  metric("doc-metric-reported-pp", "Pet Parent registrations reported", "people.pet_parents", 12, {
    isVerified: false,
    selfReported: true,
    sourceNote: "Intern-reported from campaign SG-SP27-PP-004",
    sourceSystem: "referral_tracking",
  }),
  metric("doc-metric-verified-pp", "Pet Parent registrations verified", "people.pet_parents", 9, {
    isVerified: true,
    selfReported: false,
    sourceNote: "SitGuru registration records for the assigned market",
    sourceSystem: "registration_records",
  }),
  metric("doc-metric-pending", "Instagram visits pending verification", "social.instagram", 140, {
    isVerified: false,
    selfReported: true,
    sourceNote: "Intern-reported Instagram visits",
    sourceSystem: "meta",
    finalSection: "analytics_attribution",
  }),
  metric("doc-metric-corrected", "Instagram visits corrected", "social.instagram", 118, {
    isVerified: true,
    selfReported: false,
    sourceNote: "Corrected after SitGuru tracking review",
    sourceSystem: "referral_tracking",
    finalSection: "analytics_attribution",
  }),
];

const SMART_GOALS: InternshipSmartGoal[] = [
  {
    id: "doc-smart-pp",
    internId: INTERN_ID,
    specific:
      "Increase attributable Greater Philadelphia Pet Parent registrations from campaign SG-SP27-PP-004.",
    measurable: "Verified SitGuru Pet Parent registrations in the assigned market.",
    achievable: "Move from baseline 20 toward 40 with two weekend campaigns.",
    relevant: "Pet Parent acquisition is the Market Growth Project outcome.",
    timeBound: "By March 31, 2027.",
    metricKey: "people.pet_parents",
    baselineValue: "20",
    targetValue: "40",
    sourceSystem: "registration_records",
    status: "locked",
    submittedAt: "2026-08-20T12:00:00.000Z",
    approvedAt: "2026-08-21T12:00:00.000Z",
    approvedBy: "SitGuru supervisor",
    lockedAt: "2026-08-21T12:00:00.000Z",
    changeReason: "",
  },
];

const EXPERIMENTS: InternshipExperiment[] = [
  {
    id: "doc-experiment-1",
    internId: INTERN_ID,
    hypothesis:
      "A Saturday morning Find Care CTA with unique UTM will convert more Pet Parents than a generic brand post.",
    action: "Published one Instagram post with SG-SP27-PP-004 tracking and a Book on SitGuru CTA.",
    audience: "Example University pet owners in Greater Philadelphia.",
    result: "12 intern-reported registrations; 9 SitGuru-verified.",
    lesson: "Tracking links must be in the caption. Untracked posts cannot be counted.",
    nextStep: "Repeat the weekend post with the corrected CTA and verified UTM.",
    finalSection: "pet_parent_growth",
    campaignId: DOCUMENTATION_CAMPAIGN_ID,
    internReportedResult: "12 Pet Parent registrations reported",
    verifiedResult: "9 Pet Parent registrations verified by SitGuru",
    includedInFinal: true,
  },
];

function weekly(
  id: string,
  weekOf: string,
  extra: Partial<InternshipWeeklyReview>,
): InternshipWeeklyReview {
  return {
    id,
    internId: INTERN_ID,
    weekOf,
    accomplished: extra.accomplished || "",
    dataShowed: extra.dataShowed || "",
    didntWork: extra.didntWork || "",
    changingNextWeek: extra.changingNextWeek || "",
    upcomingApproved: Boolean(extra.upcomingApproved),
    finalSection: extra.finalSection || "campaign_system",
    contributionAdded: extra.contributionAdded || "",
    hoursLogged: extra.hoursLogged ?? 8,
    workApproved: extra.workApproved,
    hoursApproved: extra.hoursApproved,
    evidenceApproved: extra.evidenceApproved,
    contributionApproved: extra.contributionApproved,
    internReportedKpi: extra.internReportedKpi || "",
    verifiedKpi: extra.verifiedKpi || "",
  };
}

const PAST_WEEKS: InternshipWeeklyReview[] = [
  weekly("doc-week-1", "2026-08-09", {
    contributionAdded: "Market map for Example University / Greater Philadelphia.",
    accomplished: "Defined the assigned market and audience.",
    dataShowed: "Baseline Pet Parent count locked at 20.",
    didntWork: "Generic city-wide targeting was too broad.",
    changingNextWeek: "Narrow to campus-adjacent ZIPs.",
    finalSection: "market_analysis",
    hoursLogged: 10,
    workApproved: true,
    hoursApproved: true,
    evidenceApproved: true,
    contributionApproved: true,
    internReportedKpi: "Baseline 20 Pet Parents",
    verifiedKpi: "20 Pet Parent registrations verified by SitGuru",
    upcomingApproved: true,
  }),
  weekly("doc-week-2", "2026-08-16", {
    contributionAdded: "SMART target: 20 to 40 Pet Parent registrations by March 31, 2027.",
    accomplished: "Wrote and submitted the primary SMART goal.",
    dataShowed: "Baseline confirmed.",
    didntWork: "Could not count untracked social clicks.",
    changingNextWeek: "Add UTM before any public post.",
    finalSection: "growth_strategy",
    hoursLogged: 9,
    workApproved: true,
    hoursApproved: true,
    evidenceApproved: true,
    contributionApproved: true,
    internReportedKpi: "Baseline 20",
    verifiedKpi: "20 verified",
    upcomingApproved: true,
  }),
  weekly("doc-week-3", "2026-08-23", {
    contributionAdded: "Pet Parent and Guru personas for the assigned market.",
    accomplished: "Finished audience strategy notes.",
    dataShowed: "No new registrations this week.",
    didntWork: "Persona interviews cannot use real customer names.",
    changingNextWeek: "Move into content pillars.",
    finalSection: "audience_strategy",
    hoursLogged: 8,
    workApproved: true,
    hoursApproved: true,
    contributionApproved: true,
    internReportedKpi: "0 new registrations",
    verifiedKpi: "0 verified",
  }),
  weekly("doc-week-4", "2026-08-30", {
    contributionAdded: "Content pillars, CTAs, and first tracking sheet.",
    accomplished: "Drafted weekend campaign copy.",
    dataShowed: "Still at baseline until tracking is live.",
    didntWork: "A post without UTM had to be discarded from the count.",
    changingNextWeek: "Launch SG-SP27-PP-004.",
    finalSection: "content_system",
    hoursLogged: 8,
    workApproved: true,
    hoursApproved: true,
    contributionApproved: true,
  }),
];

const THIS_WEEK_AWAITING = weekly("doc-week-5-awaiting", "2026-09-06", {
  contributionAdded: "Built SG-SP27-PP-004 tracking and submitted the weekend campaign package.",
  accomplished: "Created UTM links and submitted the Instagram carousel.",
  dataShowed: "12 intern-reported Pet Parent registrations; verification pending.",
  didntWork: "One TikTok hook needs a clearer Find Care CTA.",
  changingNextWeek: "Resubmit the experiment with tracking evidence.",
  finalSection: "campaign_system",
  hoursLogged: 8,
  workApproved: false,
  hoursApproved: false,
  evidenceApproved: false,
  contributionApproved: false,
  internReportedKpi: "12 Pet Parent registrations reported",
  verifiedKpi: "",
  upcomingApproved: false,
});

const THIS_WEEK_APPROVED = weekly("doc-week-5-approved", "2026-09-06", {
  contributionAdded: "Weekend Pet Parent campaign with verified tracking.",
  accomplished: "Launched SG-SP27-PP-004 and logged evidence.",
  dataShowed: "9 SitGuru-verified Pet Parent registrations vs intern-reported 12.",
  didntWork: "Untracked clicks cannot be counted.",
  changingNextWeek: "Repeat the winning CTA with the same UTM pattern.",
  finalSection: "campaign_system",
  hoursLogged: 8,
  workApproved: true,
  hoursApproved: true,
  evidenceApproved: true,
  contributionApproved: true,
  internReportedKpi: "12 Pet Parent registrations reported",
  verifiedKpi: "9 Pet Parent registrations verified by SitGuru",
  upcomingApproved: true,
});

const MILESTONES: InternshipMilestone[] = [
  {
    id: "doc-ms-university-midterm",
    cohortId: DOCUMENTATION_COHORT_ID,
    universityId: DOCUMENTATION_UNIVERSITY_ID,
    universityName: "Example University",
    key: "university_midterm",
    title: "Example University midterm evaluation due",
    dueOn: "2026-09-15",
    phase: "academic",
    owner: "university",
    action: "Submit the university evaluation form through campus systems.",
    status: "upcoming",
  },
  {
    id: "doc-ms-university-timesheet",
    cohortId: DOCUMENTATION_COHORT_ID,
    universityId: DOCUMENTATION_UNIVERSITY_ID,
    universityName: "Example University",
    key: "university_timesheet",
    title: "Example University timesheet checkpoint",
    dueOn: "2026-09-22",
    phase: "academic",
    owner: "university",
    action: "Log approved hours to the campus timesheet.",
    status: "upcoming",
  },
  {
    id: "doc-ms-sitguru-midpoint",
    cohortId: DOCUMENTATION_COHORT_ID,
    universityId: null,
    universityName: "",
    key: "sitguru_midpoint",
    title: "SitGuru midpoint Business Growth Report review",
    dueOn: "2026-09-18",
    phase: "employer",
    owner: "sitguru",
    action: "SitGuru reviews verified KPIs and weekly contributions.",
    status: "upcoming",
  },
  {
    id: "doc-ms-sitguru-campaign",
    cohortId: DOCUMENTATION_COHORT_ID,
    universityId: null,
    universityName: "",
    key: "sitguru_campaign_launch",
    title: "SitGuru weekend campaign launch",
    dueOn: "2026-09-12",
    phase: "employer",
    owner: "sitguru",
    action: "Publish only after SitGuru approves copy and tracking.",
    status: "upcoming",
  },
];

const COMMENTS: InternshipWorkComment[] = [
  {
    id: "doc-comment-1",
    internId: INTERN_ID,
    itemType: "task",
    itemId: "doc-task-07",
    authorRole: "supervisor",
    body: "Please attach the SG-SP27-PP-004 tracking URL before this can count.",
    createdAt: "2026-09-05T19:00:00.000Z",
  },
  {
    id: "doc-comment-2",
    internId: INTERN_ID,
    itemType: "task",
    itemId: "doc-task-07",
    authorRole: "intern",
    body: "Added the UTM sheet and will resubmit today.",
    createdAt: "2026-09-06T10:00:00.000Z",
  },
];

const ATTACHMENTS: InternshipWorkAttachment[] = [
  {
    id: "doc-file-task-07",
    internId: INTERN_ID,
    itemType: "task",
    itemId: "doc-task-07",
    fileName: "sg-sp27-pp-004-utm-evidence.pdf",
    fileUrl: "https://example.edu/intern/sg-sp27-pp-004-utm-evidence.pdf",
    storageBucket: "documentation",
    storagePath: "documentation/sg-sp27-pp-004-utm-evidence.pdf",
    mimeType: "application/pdf",
    fileSize: 24000,
    caption: "Example UTM evidence for the weekend campaign.",
    contributesToFinal: true,
    uploadedByRole: "intern",
    createdAt: "2026-09-06T11:00:00.000Z",
  },
  {
    id: "doc-file-week-5",
    internId: INTERN_ID,
    itemType: "weekly",
    itemId: "doc-week-5-awaiting",
    fileName: "week-5-campaign-notes.pdf",
    fileUrl: "https://example.edu/intern/week-5-campaign-notes.pdf",
    storageBucket: "documentation",
    storagePath: "documentation/week-5-campaign-notes.pdf",
    mimeType: "application/pdf",
    fileSize: 18000,
    caption: "Weekly campaign notes.",
    contributesToFinal: true,
    uploadedByRole: "intern",
    createdAt: "2026-09-06T12:00:00.000Z",
  },
  {
    id: "doc-file-campaign",
    internId: INTERN_ID,
    itemType: "campaign",
    itemId: DOCUMENTATION_CAMPAIGN_ID,
    fileName: "weekend-campaign-brief.pdf",
    fileUrl: "https://example.edu/intern/weekend-campaign-brief.pdf",
    storageBucket: "documentation",
    storagePath: "documentation/weekend-campaign-brief.pdf",
    mimeType: "application/pdf",
    fileSize: 22000,
    caption: "Campaign brief.",
    contributesToFinal: true,
    uploadedByRole: "intern",
    createdAt: "2026-09-04T12:00:00.000Z",
  },
];

function baseWorkspace(weeklyReviews: InternshipWeeklyReview[]): InternshipWorkspaceData {
  return {
    intern: {
      id: INTERN_ID,
      userId: null,
      fullName: "Taylor Morgan",
      email: "taylor.morgan@example.edu",
      studentId: "EXU-2027-441",
      studentEmail: "taylor.morgan@example.edu",
      phone: "(555) 010-0142",
      academicLevel: "junior",
      cohortId: DOCUMENTATION_COHORT_ID,
      universityId: DOCUMENTATION_UNIVERSITY_ID,
      campusId: "doc-campus-example",
      pathType: "credit_bearing",
      academicProgram: "Digital Communications",
      courseCode: "COMM 495",
      credits: 3,
      requiredHours: 120,
      facultySupervisor: "Prof. Jordan Lee",
      academicAdvisor: "Casey Nguyen",
      careerOffice: "Example University Career Center",
      academicCoordinator: "Riley Patel",
      approvalStatus: "approved",
      approvalDate: "2026-08-01",
      semester: "Spring 2027",
      academicStartDate: "2026-08-09",
      academicEndDate: "2026-12-18",
      status: "active",
      portalEnabled: true,
      academicSnapshot: { requirementId: "doc-requirement-example" },
      notes: "",
      avatarUrl: "",
      preferredName: "Taylor",
      headline: "Example University intern growing SitGuru in Greater Philadelphia",
      bio: "Documentation intern fixture. All names, emails, and metrics are fictional.",
      linkedinUrl: "https://www.linkedin.com/in/example-taylor-morgan",
      portalTheme: "emerald",
      isTest: true,
      baselineLockedAt: "2026-08-20T12:00:00.000Z",
      baselineLockReason: "Two-week SitGuru baseline captured for the Market Growth Project.",
    },
    university: {
      id: DOCUMENTATION_UNIVERSITY_ID,
      slug: "example-university",
      name: "Example University",
      displayName: "Example University",
      shortName: "Example U",
      parentUniversityId: null,
      city: "Example City",
      state: "PA",
      region: "Greater Philadelphia",
      country: "US",
      websiteUrl: "https://www.example.edu",
      status: "internship_eligible",
      isUniversityPartner: false,
      partnerNotes: "",
      partnerSince: null,
      remoteEligible: true,
      academicCreditStatus: "confirmed",
      internshipEligibilityStatus: "eligible",
      fundingStatus: "unknown",
      sourceUrl: "https://www.example.edu/internships",
      verifiedAt: "2026-08-01T12:00:00.000Z",
      notes: "",
      archived: false,
      headerTitle: "Example University Internship",
      headerProgram: "Digital Communications",
      logoUrl: "",
      logoPermissionGranted: false,
    },
    campus: {
      id: "doc-campus-example",
      universityId: DOCUMENTATION_UNIVERSITY_ID,
      slug: "example-campus",
      name: "Example Campus",
      displayName: "Example Campus",
      city: "Example City",
      state: "PA",
      isPrimary: true,
    },
    cohort: {
      id: DOCUMENTATION_COHORT_ID,
      name: "Spring 2027",
      season: "spring",
      year: 2027,
      academicYear: "2026-2027",
      startsOn: "2026-08-09",
      endsOn: "2026-12-18",
      status: "active",
    },
    projects: [
      {
        id: DOCUMENTATION_PROJECT_ID,
        cohortId: DOCUMENTATION_COHORT_ID,
        slug: "greater-philadelphia-market-growth",
        name: "Greater Philadelphia Market Growth Project",
        projectKind: "pet_parent_growth",
        baselineNotes: "Baseline 20 verified Pet Parent registrations.",
        targetNotes: "SMART target 40 verified Pet Parent registrations by March 31, 2027.",
        status: "active",
      },
    ],
    tasks: TASKS,
    content: CONTENT,
    campaigns: CAMPAIGNS,
    metrics: METRICS,
    scorecards: [],
    weeklyReviews,
    smartGoals: SMART_GOALS,
    experiments: EXPERIMENTS,
    accessGrants: [
      { toolKey: "intern_portal", granted: true, notes: "Documentation fixture", grantStatus: "active" },
    ],
    milestones: MILESTONES,
    comments: COMMENTS,
    attachments: ATTACHMENTS,
    onboarding: null,
  };
}

export function documentationInternWorkspace(
  scene: InternDocumentationScene = "default",
): InternshipWorkspaceData {
  if (scene === "checkin-form") return baseWorkspace(PAST_WEEKS);
  if (scene === "approved") return baseWorkspace([...PAST_WEEKS, THIS_WEEK_APPROVED]);
  return baseWorkspace([...PAST_WEEKS, THIS_WEEK_AWAITING]);
}

export function documentationPromoteEvents(): InternPromoteEvent[] {
  return [
    {
      id: "doc-event-park",
      title: "Example Park pet meetup",
      when: "Sat, Sep 12",
      place: "Example Park · Example City, PA",
      href: "/events",
    },
    {
      id: "doc-event-campus",
      title: "Campus club pet photo night",
      when: "Thu, Sep 17",
      place: "Example University · Example City, PA",
      href: "/events",
    },
  ];
}

export function documentationKpiSnapshot(): InternSafeKpiSnapshot {
  return {
    marketLabel: "Greater Philadelphia (example market)",
    people: {
      petParents: 29,
      gurus: 11,
      bookableGurus: 7,
      ambassadors: 4,
    },
    marketPeople: {
      petParents: 29,
      gurus: 11,
      ambassadors: 4,
    },
    social: {
      facebook: { visits: 42, scans: 6, attributed: 3 },
      instagram: { visits: 118, scans: 14, attributed: 9 },
      tiktok: { visits: 67, scans: 4, attributed: 2 },
      x: { visits: 18, scans: 1, attributed: 0 },
      youtube: { visits: 25, scans: 2, attributed: 1 },
    },
    capturedAt: "2026-09-06T16:00:00.000Z",
  };
}

function trend(delta: number) {
  const direction = delta > 0 ? "up" : delta < 0 ? "down" : "flat";
  return {
    direction,
    tone: direction === "down" ? "down" : direction === "up" ? "up" : "flat",
    delta,
    label: delta === 0 ? "even" : `${delta > 0 ? "+" : "−"}${Math.abs(delta)}`,
    srLabel: "Documentation fixture",
  } as GrowthHomeStats["trends"]["petParents"];
}

export function documentationGrowthHomeStats(): GrowthHomeStats {
  return {
    petParents: 9,
    gurus: 3,
    referrals: 14,
    visits: 118,
    signups: 9,
    conversion: "7.6%",
    campaigns: 3,
    pendingReview: 2,
    trends: {
      petParents: trend(9),
      gurus: trend(3),
      referrals: trend(4),
      visits: trend(22),
      signups: trend(9),
      conversion: trend(2),
      campaigns: trend(1),
      pendingReview: trend(-1),
    },
  };
}

export function documentationGrowthCampaigns(): GrowthCampaign[] {
  return CAMPAIGNS.map((campaign) => ({
    id: campaign.id,
    name: campaign.name,
    slug: campaign.id,
    channel: campaign.utmSource,
    channelLabel: campaign.utmSource,
    kind: "intern_campaign",
    market: "Greater Philadelphia",
    destination: campaign.trackingUrl,
    trackingUrl: campaign.trackingUrl,
    status: campaign.status,
    notes: campaign.objective,
    createdAt: "2026-08-30T12:00:00.000Z",
  }));
}

export function documentationGrowthContent(): GrowthContent[] {
  return CONTENT.map((item) => ({
    id: item.id,
    title: item.title,
    platform: item.platform,
    audience: "Example University pet owners",
    campaign: "SG-SP27-PP-004",
    status: item.status,
    plannedDate: item.dueOn,
    caption: item.studentNotes,
    owner: "Taylor Morgan",
    createdAt: "2026-09-01T12:00:00.000Z",
  }));
}
