-- 20260503_major_us_metro_marketplace_fee_rules.sql
-- SitGuru starter marketplace fee rules for major U.S. metro areas.
-- Safe to run more than once because it skips existing locality_name values.

create extension if not exists pgcrypto;

with starter_rules (
  locality_name,
  description,
  country,
  state,
  city,
  postal_code,
  latitude,
  longitude,
  radius_miles,
  fee_percent,
  priority,
  is_active
) as (
  values
    -- 20% dense / high-cost cores
    (
      'New York City Core',
      'Dense high-cost core marketplace fee rule for Manhattan and nearby NYC care markets.',
      'US',
      'NY',
      'New York',
      null,
      40.7580,
      -73.9855,
      12,
      20,
      40,
      true
    ),
    (
      'San Francisco Core',
      'Dense high-cost core marketplace fee rule for San Francisco.',
      'US',
      'CA',
      'San Francisco',
      null,
      37.7749,
      -122.4194,
      12,
      20,
      40,
      true
    ),
    (
      'Seattle Core',
      'Dense high-cost core marketplace fee rule for Seattle.',
      'US',
      'WA',
      'Seattle',
      null,
      47.6062,
      -122.3321,
      10,
      19,
      45,
      true
    ),
    (
      'Boston Core',
      'Dense high-cost core marketplace fee rule for Boston.',
      'US',
      'MA',
      'Boston',
      null,
      42.3601,
      -71.0589,
      12,
      19,
      45,
      true
    ),
    (
      'Washington DC Core',
      'Dense high-cost core marketplace fee rule for Washington DC.',
      'US',
      'DC',
      'Washington',
      null,
      38.9072,
      -77.0369,
      12,
      19,
      45,
      true
    ),
    (
      'Los Angeles Core',
      'Dense high-cost core marketplace fee rule for central Los Angeles.',
      'US',
      'CA',
      'Los Angeles',
      null,
      34.0522,
      -118.2437,
      14,
      19,
      45,
      true
    ),
    (
      'Miami Core',
      'Dense high-demand core marketplace fee rule for Miami.',
      'US',
      'FL',
      'Miami',
      null,
      25.7617,
      -80.1918,
      12,
      19,
      45,
      true
    ),

    -- 18% to 19% major metro rules
    (
      'New York City Metro',
      'Major metro marketplace fee rule for the broader NYC area.',
      'US',
      'NY',
      'New York',
      null,
      40.7128,
      -74.0060,
      35,
      20,
      70,
      true
    ),
    (
      'Los Angeles Metro',
      'Major metro marketplace fee rule for the broader Los Angeles area.',
      'US',
      'CA',
      'Los Angeles',
      null,
      34.0522,
      -118.2437,
      35,
      19,
      75,
      true
    ),
    (
      'San Francisco Bay Area',
      'Major metro marketplace fee rule for San Francisco and the surrounding Bay Area.',
      'US',
      'CA',
      'San Francisco',
      null,
      37.7749,
      -122.4194,
      35,
      20,
      70,
      true
    ),
    (
      'Chicago Metro',
      'Major metro marketplace fee rule for the broader Chicago area.',
      'US',
      'IL',
      'Chicago',
      null,
      41.8781,
      -87.6298,
      30,
      18,
      80,
      true
    ),
    (
      'Dallas Fort Worth Metro',
      'Major metro marketplace fee rule for Dallas Fort Worth.',
      'US',
      'TX',
      'Dallas',
      null,
      32.7767,
      -96.7970,
      40,
      17,
      90,
      true
    ),
    (
      'Houston Metro',
      'Major metro marketplace fee rule for the broader Houston area.',
      'US',
      'TX',
      'Houston',
      null,
      29.7604,
      -95.3698,
      35,
      17,
      90,
      true
    ),
    (
      'Washington DC Metro',
      'Major metro marketplace fee rule for the broader Washington DC area.',
      'US',
      'DC',
      'Washington',
      null,
      38.9072,
      -77.0369,
      30,
      18,
      80,
      true
    ),
    (
      'Miami Fort Lauderdale Metro',
      'Major metro marketplace fee rule for Miami and Fort Lauderdale.',
      'US',
      'FL',
      'Miami',
      null,
      25.7617,
      -80.1918,
      35,
      18,
      80,
      true
    ),
    (
      'Atlanta Metro',
      'Major metro marketplace fee rule for the broader Atlanta area.',
      'US',
      'GA',
      'Atlanta',
      null,
      33.7490,
      -84.3880,
      35,
      17,
      90,
      true
    ),
    (
      'Phoenix Metro',
      'Major metro marketplace fee rule for the broader Phoenix area.',
      'US',
      'AZ',
      'Phoenix',
      null,
      33.4484,
      -112.0740,
      35,
      17,
      90,
      true
    ),
    (
      'Boston Metro',
      'Major metro marketplace fee rule for the broader Boston area.',
      'US',
      'MA',
      'Boston',
      null,
      42.3601,
      -71.0589,
      28,
      18,
      80,
      true
    ),
    (
      'Seattle Metro',
      'Major metro marketplace fee rule for the broader Seattle area.',
      'US',
      'WA',
      'Seattle',
      null,
      47.6062,
      -122.3321,
      30,
      18,
      80,
      true
    ),
    (
      'San Diego Metro',
      'Major metro marketplace fee rule for the broader San Diego area.',
      'US',
      'CA',
      'San Diego',
      null,
      32.7157,
      -117.1611,
      28,
      18,
      85,
      true
    ),
    (
      'Denver Metro',
      'Major metro marketplace fee rule for the broader Denver area.',
      'US',
      'CO',
      'Denver',
      null,
      39.7392,
      -104.9903,
      30,
      17,
      90,
      true
    ),
    (
      'Austin Metro',
      'Major metro marketplace fee rule for the broader Austin area.',
      'US',
      'TX',
      'Austin',
      null,
      30.2672,
      -97.7431,
      30,
      17,
      90,
      true
    ),
    (
      'Tampa Bay Metro',
      'Major metro marketplace fee rule for Tampa Bay.',
      'US',
      'FL',
      'Tampa',
      null,
      27.9506,
      -82.4572,
      35,
      17,
      90,
      true
    ),
    (
      'Orlando Metro',
      'Major metro marketplace fee rule for the broader Orlando area.',
      'US',
      'FL',
      'Orlando',
      null,
      28.5383,
      -81.3792,
      30,
      17,
      90,
      true
    ),
    (
      'Minneapolis Saint Paul Metro',
      'Major metro marketplace fee rule for the Twin Cities area.',
      'US',
      'MN',
      'Minneapolis',
      null,
      44.9778,
      -93.2650,
      32,
      17,
      90,
      true
    ),
    (
      'Portland Metro',
      'Major metro marketplace fee rule for the broader Portland area.',
      'US',
      'OR',
      'Portland',
      null,
      45.5152,
      -122.6784,
      28,
      17,
      90,
      true
    ),
    (
      'Charlotte Metro',
      'Major metro marketplace fee rule for the broader Charlotte area.',
      'US',
      'NC',
      'Charlotte',
      null,
      35.2271,
      -80.8431,
      30,
      16,
      100,
      true
    ),
    (
      'Nashville Metro',
      'Major metro marketplace fee rule for the broader Nashville area.',
      'US',
      'TN',
      'Nashville',
      null,
      36.1627,
      -86.7816,
      30,
      16,
      100,
      true
    ),
    (
      'Raleigh Durham Metro',
      'Major metro marketplace fee rule for the Raleigh Durham area.',
      'US',
      'NC',
      'Raleigh',
      null,
      35.7796,
      -78.6382,
      30,
      16,
      100,
      true
    ),
    (
      'Las Vegas Metro',
      'Major metro marketplace fee rule for the broader Las Vegas area.',
      'US',
      'NV',
      'Las Vegas',
      null,
      36.1699,
      -115.1398,
      28,
      17,
      90,
      true
    ),
    (
      'Sacramento Metro',
      'Major metro marketplace fee rule for the broader Sacramento area.',
      'US',
      'CA',
      'Sacramento',
      null,
      38.5816,
      -121.4944,
      28,
      17,
      90,
      true
    ),
    (
      'Baltimore Metro',
      'Major metro marketplace fee rule for the broader Baltimore area.',
      'US',
      'MD',
      'Baltimore',
      null,
      39.2904,
      -76.6122,
      28,
      17,
      90,
      true
    ),
    (
      'Detroit Metro',
      'Major metro marketplace fee rule for the broader Detroit area.',
      'US',
      'MI',
      'Detroit',
      null,
      42.3314,
      -83.0458,
      30,
      16,
      100,
      true
    ),
    (
      'Pittsburgh Metro',
      'Major metro marketplace fee rule for the broader Pittsburgh area.',
      'US',
      'PA',
      'Pittsburgh',
      null,
      40.4406,
      -79.9959,
      28,
      16,
      100,
      true
    ),
    (
      'Cleveland Metro',
      'Major metro marketplace fee rule for the broader Cleveland area.',
      'US',
      'OH',
      'Cleveland',
      null,
      41.4993,
      -81.6944,
      28,
      16,
      100,
      true
    ),
    (
      'Columbus Metro',
      'Major metro marketplace fee rule for the broader Columbus area.',
      'US',
      'OH',
      'Columbus',
      null,
      39.9612,
      -82.9988,
      28,
      16,
      100,
      true
    ),
    (
      'Indianapolis Metro',
      'Major metro marketplace fee rule for the broader Indianapolis area.',
      'US',
      'IN',
      'Indianapolis',
      null,
      39.7684,
      -86.1581,
      28,
      16,
      100,
      true
    ),
    (
      'Kansas City Metro',
      'Major metro marketplace fee rule for the broader Kansas City area.',
      'US',
      'MO',
      'Kansas City',
      null,
      39.0997,
      -94.5786,
      30,
      16,
      100,
      true
    ),
    (
      'Saint Louis Metro',
      'Major metro marketplace fee rule for the broader Saint Louis area.',
      'US',
      'MO',
      'Saint Louis',
      null,
      38.6270,
      -90.1994,
      28,
      16,
      100,
      true
    ),
    (
      'Salt Lake City Metro',
      'Major metro marketplace fee rule for the broader Salt Lake City area.',
      'US',
      'UT',
      'Salt Lake City',
      null,
      40.7608,
      -111.8910,
      30,
      16,
      100,
      true
    ),
    (
      'San Antonio Metro',
      'Major metro marketplace fee rule for the broader San Antonio area.',
      'US',
      'TX',
      'San Antonio',
      null,
      29.4241,
      -98.4936,
      30,
      16,
      100,
      true
    ),
    (
      'Jacksonville Metro',
      'Major metro marketplace fee rule for the broader Jacksonville area.',
      'US',
      'FL',
      'Jacksonville',
      null,
      30.3322,
      -81.6557,
      30,
      16,
      100,
      true
    ),
    (
      'New Orleans Metro',
      'Major metro marketplace fee rule for the broader New Orleans area.',
      'US',
      'LA',
      'New Orleans',
      null,
      29.9511,
      -90.0715,
      28,
      16,
      100,
      true
    ),
    (
      'Honolulu Metro',
      'Major metro marketplace fee rule for Honolulu.',
      'US',
      'HI',
      'Honolulu',
      null,
      21.3069,
      -157.8583,
      24,
      18,
      80,
      true
    )
)
insert into public.marketplace_fee_rules (
  locality_name,
  description,
  country,
  state,
  city,
  postal_code,
  latitude,
  longitude,
  radius_miles,
  fee_percent,
  priority,
  is_active
)
select
  starter_rules.locality_name,
  starter_rules.description,
  starter_rules.country,
  starter_rules.state,
  starter_rules.city,
  starter_rules.postal_code,
  starter_rules.latitude,
  starter_rules.longitude,
  starter_rules.radius_miles,
  starter_rules.fee_percent,
  starter_rules.priority,
  starter_rules.is_active
from starter_rules
where not exists (
  select 1
  from public.marketplace_fee_rules existing
  where lower(existing.locality_name) = lower(starter_rules.locality_name)
);